apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-bonde-data
  namespace: bonde-org
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi