apiVersion: v1
kind: Service
metadata:
  name: wp-bonde
  namespace: bonde-org
  labels:
    app: wp-bonde
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: wp-bonde