apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-nossas
  namespace: bonde-org
  labels:
    app: cms-nossas
    component: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-nossas
  template:
    metadata:
      labels:
        app: cms-nossas
    spec:
      containers:
      - name: cms-nossas
        image: nossas/nossas-cms:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "org_nossas.nossas.settings.production"
        - name: DEBUG
          value: "False"
        - name: AWS_STORAGE_BUCKET_NAME
          value: "openactiontool-cms"
        - name: DISABLE_RECAPTCHA
          value: "False"
        - name: BONDE_ACTION_API_URL
          value: "http://api-graphql:80/v1/graphql"
        - name: ALLOWED_HOSTS
          value: "nossas.org,www.nossas.org"
        - name: ADMINS
          value: "('BONDE', 'suporte@bonde.org'),"
        - name: BONDE_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bonde-database-url
              key: BONDE_DATABASE_URL
        - name: CMS_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nossas-database-url
              key: CMS_DATABASE_URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-access-key
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret-key
              key: AWS_SECRET_ACCESS_KEY
        - name: BONDE_ACTION_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: action-secret
              key: BONDE_ACTION_SECRET_KEY
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: SMTP_USER
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: SMTP_PASS
        resources:
          requests:
            memory: "500Mi"
            cpu: "50m"
          limits:
            memory: "1000Mi"
            cpu: "200m"