"""Add hosted_zone_id to bidirectional check relationship Route53 x app

Revision ID: 0b14dc411037
Revises: f08ac88e9041
Create Date: 2024-10-09 11:22:30.614982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b14dc411037'
down_revision = 'f08ac88e9041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hosted_zone_id', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_column('hosted_zone_id')

    # ### end Alembic commands ###
