"""Add external_id column to Domain

Revision ID: 774eccbc9ad7
Revises: a311a5120975
Create Date: 2024-10-05 17:53:58.559769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774eccbc9ad7'
down_revision = 'a311a5120975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
