"""Add has_manage_dns field to Domain

Revision ID: f08ac88e9041
Revises: 58141824e588
Create Date: 2024-10-08 18:42:00.255124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08ac88e9041'
down_revision = '58141824e588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_manage_dns', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_column('has_manage_dns')

    # ### end Alembic commands ###
