services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - projetotrilhas_wp_data:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.services.wordpress.loadbalancer.server.port=80
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.tls.certresolver=myresolver
      - traefik.http.routers.wordpress.rule=${TRAEFIK_ROUTERS_RULE:-HostRegexp(`wordpress.bonde.org`)}

volumes:
  projetotrilhas_wp_data:
    driver: local

# Todos os serviços devem pertencer a mesma rede para serem descobertos pelo Traefik
networks:
  default:
    # Padronizar o nome da rede com o nome do domínio
    name: web
