# Generated by Django 5.1.2 on 2024-10-21 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_tools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HttpRouter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=30, unique=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("schema_history", models.JSONField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="domain",
            name="http_router",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domains",
                to="website_tools.httprouter",
            ),
        ),
    ]
