# Generated by Django 5.1.2 on 2024-10-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_tools", "0002_httprouter_domain_http_router"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="http_router",
        ),
        migrations.AddField(
            model_name="httprouter",
            name="domains",
            field=models.ManyToManyField(
                related_name="http_routers", to="website_tools.domain"
            ),
        ),
    ]
