apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: tools
  labels:
    app: metabase
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: metabase