# Generated by Django 5.1.2 on 2024-10-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Site",
            new_name="SiteProject",
        ),
    ]
