# Generated by Django 5.1.2 on 2024-10-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_site_siteproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="external_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
