apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-data
  namespace: bonde-org
  labels:
    app: api-data
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-data
  template:
    metadata:
      labels:
        app: api-data
    spec:
      containers:
      - name: api-data
        image: nossas/bonde-an-web-fastapi:latest
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bonde-database-url-v2
              key: DATABASE_URL
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "200m"