apiVersion: v1
kind: Service
metadata:
  name: api-actions
  namespace: bonde-org
  labels:
    app: api-actions
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: api-actions